owner: levackt
repo: upptime-1

sites:
  - name: Holodeck explorer
    url: https://explorer.secrettestnet.io/
  - name: Faucet
    url: https://faucet.secrettestnet.io/
  - name: LCD
    url: https://chainofsecrets.secrettestnet.io/
  - name: RPC
    url: https://chainofsecrets.secrettestnet.io:26667/

status-website:
  baseUrl: /levackt/upptime-1
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Holodeck Upptime
  introTitle: "Holodeck Upptime monitor"
  introMessage: Holodeck uptime **real-time** data
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
